version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
clone_depth: 2
before_build:
- cmd: >-
    git submodule init

    git submodule update

    nuget restore
build:
  project: SetStartupProjectVS.sln
  verbosity: minimal
artifacts:
- path: SetStartupProjectVS\bin\$(configuration)\*.vsix
  name: vsix
